projects:
  elucid:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        graphQLApiId: tsoacp6qtrdb5ktgtbzhy5fpyu
      endpoints:
        prod: >-
          https://bevitly75rhyzmu5ftuew34bv4.appsync-api.us-east-2.amazonaws.com/graphql
